import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "./Components/app-sidebar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import React from "react";
import StoreProvider from "./store/StoreProvider";
import { Navbar } from "./Components/NavBar";
import { Jura  } from "next/font/google";

const roboto = Jura({
  subsets: ["latin"],
  // weight: ["100", "400", "700", "900"], // Ensure these are valid weights
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <SpeedInsights />
      <html lang="en">
        <body
          className={`${roboto.className}  antialiased w-full bg-gray-300 text-secondary-foreground`}
        >
          <SidebarProvider className="relative">
            <AppSidebar />
            <main className="w-full min-h-[100vh] pt-2 pb-6 px-3">
              <Navbar />
              <div className="pt-14">{children}</div>
            </main>
          </SidebarProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
