import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "./Components/app-sidebar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import React from "react";
import StoreProvider from "./store/StoreProvider";
import { Navbar } from "./Components/NavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <SpeedInsights />
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full bg-gray-300 text-foreground`}
        >
          <SidebarProvider className="relative">
            <AppSidebar />
            <main className="w-full min-h-[100vh] py-2 pe-3">
              <Navbar />
              <div className="pt-3">

              </div>
                {children}
            </main>
          </SidebarProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
